all:
	clang -Wall -target hexagon -c test.c -o test.o
	clang -Wall -target hexagon -c test.c -o test_o1.o -O1
	clang -Wall -target hexagon -c test.c -o test_o2.o -O2
	clang -Wall -target hexagon -c test.c -o test_o3.o -O3
